## -*- encoding: utf-8 -*-
## This file (burnside.sagetex.sage) was *autogenerated* from burnside.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('burnside', version='2021/10/16 v3.6', version_check=True)
_st_.useimagemagick = True
_st_.current_tex_line = 266
_st_.blockbegin()
try:
 def plotRubiks2x2(P, F, c):
     return
except:
 _st_.goboom(269)
_st_.blockend()
_st_.endofdoc()
